### ISSUE TITLE
What does "Enable safe mode" do?

### ISSUE THREAD

**Issue by shangles** [bakkesmodorg/BakkesModInjectorCpp#12]
Sorry for posting here but I can't find info on this in the BakkesMod wiki or on Discord FAQ.

I noticed in my Windows client there's an "Enable safe mode" option in the Settings menu that is checked.  I'm just looking for clarification on what this does and when it should be used.  Perhaps this info should be added to the wiki?

**Comment by Bakkes** [comment]
Disabling this option will skip the version check, so it will always try to inject into a running rocket league process even if there's a version mismatch between the mod and the game. Disabling it doesn't really do much anymore since the DLL now also has version checks in it, its mostly kept it so we can test other versions of the DLL with the current Rocket League.

**Comment by tiredsdinger-max** [comment]
Pee 🔢 💯
